const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const wSpitiItinerary = [
  { day: 1, title: 'Journey to Chandigrah from your city', description: '• Starting location: Your city\n• Destination: Chandigarh\n• Transport details: Overnight train journey passing through Gujarat, Rajasthan, and Haryana.\n• Activities and sightseeing: Enjoy scenic views, bond with fellow travelers through fun activities, and soak in the local flavors at stops like Abu Road and Jaipur.\n• Important instructions: Please note that if you have a connecting train from any station in Ahmedabad or Gandhinagar to Surat, Baroda, Mumbai, or Pune inter-station transfers are not included in our package.' },
  { day: 2, title: 'Chandigarh to Narkanda', description: '• Departure/reporting time: Arrive at Chandigarh Railway Station and meet your tour leader.\n• Transport details: Scenic drive to Narkanda via Shimla with snow-capped mountain views.\n• Activities and sightseeing: Evening leisure.\n• Meals: Dinner Included\n• Hotel/stay: Hotel/Homestay in Narkanda' },
  { day: 3, title: 'Narkanda to Chitkul | Stay in Sangla', description: '• Transport details: Drive through the stunning Baspa Valley.\n• Activities and sightseeing: Explore Chitkul, India’s last inhabited village near the Indo-Tibet border.\n• Meals: Breakfast, Dinner Included\n• Hotel/stay: Homestay in sangla/Chitkul' },
  { day: 4, title: 'Sangla to Tabo via Khab Sangam & Nako Lake', description: '• Activities and sightseeing: Visit Khab Sangam (confluence of Spiti and Sutlej Rivers). Stop at Nako Lake, a frozen paradise in winter.\n• Meals: Breakfast, Dinner Included\n• Hotel/stay: Homestay in Tabo' },
  { day: 5, title: 'Tabo to Kaza via Lingti Falls, Key & Chicham', description: '• Activities and sightseeing: Visit Tabo Monastery, Key Monastery, and Chicham Bridge (Asia’s highest). Stop at Lingti Falls (frozen waterfall in winter).\n• Meals: Breakfast, Dinner Included\n• Hotel/stay: Homestay in Kaza' },
  { day: 6, title: 'Hikkim, Komic & Langza | Stay in Kaza', description: '• Activities and sightseeing: Explore Hikkim (world’s highest post office), Komic (world’s highest village), and Langza village.\n• Meals: Breakfast, Dinner Included\n• Hotel/stay: Hotel in Kaza' },
  { day: 7, title: 'Kaza to Kalpa via Dhankar', description: '• Activities and sightseeing: Visit Dhankar Monastery and Lake before descending to Kalpa. Views of Kinner Kailash.\n• Meals: Breakfast, Dinner Included\n• Hotel/stay: Hotel in Kalpa' },
  { day: 8, title: 'Kalpa to Shimla | Local Sightseeing', description: '• Transport details: Scenic drive to Shimla.\n• Activities and sightseeing: Explore Mall Road, Christ Church, and Jakhu Temple.\n• Important instructions: Please keep in mind that if group departs early morning from kalpa then we will be able to explore all above places peacefully.\n• Meals: Breakfast, Dinner Included\n• Hotel/stay: Hotel in Shimla' },
  { day: 9, title: 'Shimla to Chandigarh | Train to Ahmedabad', description: '• Transport details: Drive to Chandigarh Railway Station. Board overnight train to Ahmedabad.\n• Meals: Breakfast Included' },
  { day: 10, title: 'Arrival in Ahmedabad', description: '• Destination: Ahmedabad\n• Activities and sightseeing: Arrive in Ahmedabad with unforgettable winter memories of Himachal & Spiti Valley.' }
];

const keralaItinerary = [
  { day: 1, title: 'Ahmedabad to Cochin Train Journey', description: '• Transport details: Comfortable overnight train journey from Ahmedabad to Kochi.\n• Important instructions: Upon arrival, guests are requested to make their own arrangements for transportation from the railway station to the hotel, as transfers on this day are not included in the package.' },
  { day: 2, title: 'Arrival in Cochin', description: '• Departure/reporting time: Arriving at Ernakulam Junction around 9:00 PM.\n• Important instructions: Proceed to your hotel near the railway station and settle in after your long train journey. Take the evening to relax and recharge, as no sightseeing is scheduled today.\n• Hotel/stay: Hotel in Cochin' },
  { day: 3, title: 'Scenic Drive to Munnar', description: '• Transport details: Warm pick-up from your respective Hotel. Breathtaking drive to Munnar through lush green hills and misty landscapes.\n• Activities and sightseeing: Witness the beauty of the stunning Valara & Cheeyappara Waterfalls and explore aromatic Spice Plantations, where Kerala’s famous spices are grown.\n• Meals: Breakfast & Dinner Included\n• Hotel/stay: Hotel in Munnar' },
  { day: 4, title: 'Explore the Beauty of Munnar', description: '• Activities and sightseeing: Explore the scenic highlights of Munnar, including the peaceful Mattupetty Dam, the magical Echo Point, and the picturesque Kundala Dam. Visit the famous Eravikulam National Park (subject to government guidelines). Also explore the vibrant Rose Garden and enjoy some free time for local shopping and café hopping.\n• Meals: Breakfast & Dinner Included\n• Hotel/stay: Hotel in Munnar' },
  { day: 5, title: 'Thekkady – Wildlife & Cultural Experience', description: '• Departure/reporting time: Check out by 8:00 AM.\n• Transport details: Scenic drive to Thekkady.\n• Activities and sightseeing: Afternoon experience the peaceful Periyar Lake cruise (optional, direct payment). Enjoy an elephant interaction experience at Periyar. Evening witness Kerala’s rich traditions with the mesmerizing Kalaripayattu martial arts and Kathakali cultural show.\n• Meals: Breakfast & Dinner Included\n• Hotel/stay: Hotel stay in Thekkady' },
  { day: 6, title: 'Thekkady to Alleppey – Backwater Paradise', description: '• Transport details: Proceed to Alleppey, known as the “Venice of the East.”\n• Activities and sightseeing: Experience the beauty of Kerala’s famous backwaters with an optional boat ride (direct payment). Cruise through peaceful canals.\n• Meals: Breakfast, Lunch & Dinner Included\n• Hotel/stay: Hotel/Houseboat Alleppey\n• Important instructions: For stay in Alleppey House Boat AC timing will be from 9:00 PM to 6:00 AM.' },
  { day: 7, title: 'Alleppey to Cochin', description: '• Transport details: Scenic drive back to Kochi.\n• Activities and sightseeing: Explore the charming streets of Fort Kochi, admire the iconic Chinese Fishing Nets, and enjoy some free time for local shopping if time permits.\n• Meals: Breakfast Included\n• Hotel/stay: Hotel in Cochin' },
  { day: 8, title: 'Cochin to Ahmedabad', description: '• Transport details: Proceed to Ernakulam Railway Station to board your train to Ahmedabad.\n• Important instructions: Transportation from the railway station to the hotel is not included and should be arranged by the participants.\n• Meals: Breakfast Included. Dinner on this day is also self-paid.' },
  { day: 9, title: 'Arrival in Ahmedabad', description: '• Destination: Ahmedabad\n• Activities and sightseeing: Arrive back in Ahmedabad with countless memories, new friendships, and amazing experiences to cherish forever.' }
];

async function run() {
  await prisma.trip.update({ where: { id: 'WSPT-1' }, data: { itinerary: wSpitiItinerary } });
  await prisma.trip.update({ where: { id: 'KRL-1' }, data: { itinerary: keralaItinerary } });
  console.log("Updated WSPT-1 and KRL-1 with perfect extraction formatting.");
}
run().catch(console.error).finally(() => prisma.$disconnect());
